### ISSUE TITLE
It does not support php session serialization format

### ISSUE THREAD

**Issue by 350050183** [ironpinguin/serialized-php-parser#4]
format list this:
foo|s:17:"php session value";arr|a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}
not like:
O:8:"TypeName":1:{s:3:"foo";s:3:"bar";}

**Comment by ooxi** [comment]
Could you please elaborate?

**Comment by 350050183** [comment]
I saved session to memcache by php:

<?php    
    session_start();
    $_SESSION['foo']='bar';
    $_SESSION['iamarraykey']=array(1,2,3);
    print_r($_SESSION);
?>


and read by Java from memcache,the result is:
 foo|s:3:"bar";iamarraykey|a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}

You see,there are key-value pairs,but serialized-php-parser can only parse single value not with key,and it exhibited exception:Unknow type : f, because here the first characer is "f"( foo ).

**Comment by ooxi** [comment]
I't seams like your logic for saving the session into memcached is flawed since the session content should be

    a:2:{s:3:"foo";s:3:"bar";s:11:"iamarraykey";a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}}

Try executing this snipped for verification

````
<?php

$_SESSION['foo'] = 'bar';
$_SESSION['iamarraykey'] = array(1, 2, 3);

echo serialize($_SESSION);
````

Moreover the following unit test verifies the correct behaviour

````
SerializedPhpParser parser = new SerializedPhpParser("a:2:{s:3:\"foo\";s:3:\"bar\";s:11:\"iamarraykey\";a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}}");
Object parsed = parser.parse();
		
assert_().that(parsed).isInstanceOf(Map.class);
Map<String, Object> map = (Map<String, Object>)parsed;
		
assert_().that(map.keySet()).containsExactly("foo", "iamarraykey");
assert_().that(map.get("foo")).isEqualTo("bar");
assert_().that(map.get("iamarraykey")).isInstanceOf(Map.class);
		
Map<Long, Object> iamarraykey = (Map<Long, Object>)map.get("iamarraykey");
assert_().that(iamarraykey.get(0l)).isEqualTo(1l);
assert_().that(iamarraykey.get(1l)).isEqualTo(2l);
assert_().that(iamarraykey.get(2l)).isEqualTo(3l);
````

**Comment by 350050183** [comment]
Exactly call serialize($_SESSION) will generate string like a:2:{s:3:"foo";s:3:"bar";s:11:"iamarraykey";a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}},but if you read it from memcached or php session file directly,it should be foo|s:3:"bar";iamarraykey|a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}.

**Comment by ooxi** [comment]
Ah! Now I get your input :)

[serialized-php-parser](https://github.com/ironpinguin/serialized-php-parser/) is a Java library aiming at providing a Java implementation for [PHP's `unserialize`](http://php.net/manual/en/function.unserialize.php). It is *not* an implementation of [PHP's `session_decode`](http://php.net/manual/en/function.session-decode.php).

Note that it's very hard to produce a Java implementation for `session_decode` since you have to take [`session.serialize_handler`](http://php.net/manual/en/session.configuration.php#ini.session.serialize-handler) into account (which is not solvable in the general case).

If you have control over the PHP part of your application I suggest implementing a custom `session.serialize_handler` using [`serialize`](http://php.net/manual/en/function.serialize.php) and [`unserialize`](http://php.net/manual/en/function.unserialize.php)

**Comment by 350050183** [comment]
:) THANKS!
It seems php session serialize is different from normal way,but custom session save handler or session.serialize_handler need extra efforts,its not good for maintenance.

**Comment by ooxi** [comment]
I'll look into the effort of implementing the default behaviour of `session_decode` but I cannot promise a release of such functionality. It seams like the `session_decode` behaviour can depend on the PHP version.
